export const ActionTypes = {
    // Register Types
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    // Login Types
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    // Define your action types
    CREATE_NOTE_REQUEST: "CREATE_NOTE_REQUEST",
    CREATE_NOTE_SUCCESS: "CREATE_NOTE_SUCCESS",
    CREATE_NOTE_FAILURE: "CREATE_NOTE_FAILURE",

    // Types for list notes
    LIST_NOTES_REQUEST: "LIST_NOTES_REQUEST",
    LIST_NOTES_SUCCESS: "LIST_NOTES_SUCCESS",
    LIST_NOTES_FAILURE: "LIST_NOTES_FAILURE",

    // Types for delete notes
    DELETE_NOTE_REQUEST: 'DELETE_NOTE_REQUEST',
    DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS',
    DELETE_NOTE_FAILURE: 'DELETE_NOTE_FAILURE',

    // Types for view notes
    VIEW_NOTE_REQUEST: 'VIEW_NOTE_REQUEST',
    VIEW_NOTE_SUCCESS: 'VIEW_NOTE_SUCCESS',
    VIEW_NOTE_FAILURE: 'VIEW_NOTE_FAILURE',

    // Types for edit notes
    EDIT_NOTE_REQUEST: 'EDIT_NOTE_REQUEST',
    EDIT_NOTE_SUCCESS: 'EDIT_NOTE_SUCCESS',
    EDIT_NOTE_FAILURE: 'EDIT_NOTE_FAILURE',

    // Types for selected delete  notes
    DELETE_SELECTED_NOTES_REQUEST: 'DELETE_SELECTED_NOTES_REQUEST',
    DELETE_SELECTED_NOTES_FAILURE: 'DELETE_SELECTED_NOTES_FAILURE',
    DELETE_SELECTED_NOTES_SUCCESS: 'DELETE_SELECTED_NOTES_SUCCESS'
};